// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCikukIqs1f3OM1am4IGk5WkkqNEDgn_rI',
    appId: '1:1066168550218:web:e8f68073479e371503f7b3',
    messagingSenderId: '1066168550218',
    projectId: 'catalogo-firebase-android',
    authDomain: 'catalogo-firebase-android.firebaseapp.com',
    storageBucket: 'catalogo-firebase-android.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkHQsxeQ7VH3FV6mUMO9NqTd5rMbOAexU',
    appId: '1:1066168550218:android:ae7618640def028403f7b3',
    messagingSenderId: '1066168550218',
    projectId: 'catalogo-firebase-android',
    storageBucket: 'catalogo-firebase-android.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2SPalbUu_mKsqDtkzBmbddyeXJZgESVE',
    appId: '1:1066168550218:ios:b3aeafa76b91832c03f7b3',
    messagingSenderId: '1066168550218',
    projectId: 'catalogo-firebase-android',
    storageBucket: 'catalogo-firebase-android.appspot.com',
    iosClientId: '1066168550218-qil3n7kfcifl4uqao3kqljsht7ilg6kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2SPalbUu_mKsqDtkzBmbddyeXJZgESVE',
    appId: '1:1066168550218:ios:b3aeafa76b91832c03f7b3',
    messagingSenderId: '1066168550218',
    projectId: 'catalogo-firebase-android',
    storageBucket: 'catalogo-firebase-android.appspot.com',
    iosClientId: '1066168550218-qil3n7kfcifl4uqao3kqljsht7ilg6kh.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogo',
  );
}
